[debug] [2020-04-12T21:37:02.197Z] ----------------------------------------------------------------------
[debug] [2020-04-12T21:37:02.199Z] Command:       /usr/local/Cellar/node/12.10.0/bin/node /usr/local/bin/firebase init
[debug] [2020-04-12T21:37:02.199Z] CLI Version:   8.0.2
[debug] [2020-04-12T21:37:02.199Z] Platform:      darwin
[debug] [2020-04-12T21:37:02.199Z] Node Version:  v12.10.0
[debug] [2020-04-12T21:37:02.200Z] Time:          Sun Apr 12 2020 14:37:02 GMT-0700 (Pacific Daylight Time)
[debug] [2020-04-12T21:37:02.200Z] ----------------------------------------------------------------------
[debug] [2020-04-12T21:37:02.200Z] 
[debug] [2020-04-12T21:37:02.207Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-12T21:37:02.239Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
